### ISSUE TITLE
师傅是还没有写完么，我是用action 编译后 burp 加载的一些疑问

### ISSUE THREAD

**Issue by Mr-xn** [0nise/burp-fofa#9]
如题，是我姿势不对么。我的fork 这里有便宜好的：https://github.com/Mr-xn/burp-fofa
我下载target里的jar包，burp加载后，tab是有这个选项，但是是空白，在 proxy 目录是可以将历史的某一条 发送到 burp-fofa，但是没反应。
应该不是我修改了 source依赖版本吧 我从 6 修改成 8 
![image](https://user-images.githubusercontent.com/18260135/111058271-605d8780-84c8-11eb-8ed5-b343b3459aa4.png)
![image](https://user-images.githubusercontent.com/18260135/111058285-7bc89280-84c8-11eb-9188-c638439a12ad.png)

**Comment by 0nise** [comment]
工具没有写完
